AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template will build out the IAM Roles for Tag Compliance

Resources:
  TagComplianceEc2Policy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: Cost-Compliance-EC2-Policy
      Description: EC2 read/write access for Tag Compliance
      Roles: 
        - !Ref TagComplianceEc2Role
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ec2:Describe*'
              - 'ec2:TerminateInstances'
              - 'ec2:DeleteTags'
              - 'ec2:CreateTags'
              - 'ec2:StopInstances'
              - 'ec2:CreateSnapshot'
            Resource: '*'

  TagComplianceEc2Role:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - 
            Effect: 'Allow'
            Principal: 
              Service: 
                - 'lambda.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      Path: '/'
      RoleName: Lambda-Execution-Role-For-Cost-Compliance
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'